kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: mts-ssd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi